// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type UserInfoReq struct {
	ID string `json:"id"`
}

type UserInfoResp struct {
	Name string `json:"name"`
}
