// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Account   string `form:"account"`
	Password  string `form:"password"`
	Captcha   string `form:"captcha"`
	SessionID string `form:"sessionId"`
}

type CommonResponse struct {
	Code int64       `json:"code"`
	Data interface{} `json:"data"`
	Msg  string      `json:"msg"`
}

type EmptyRequest struct {
}
