// Code generated by goctl. DO NOT EDIT.
package types

type UserResponse struct {
	ID           string   `json:"id"`
	Nickname     string   `json:"nickname"`
	Avatar       string   `json:"avatar"`
	Account      string   `json:"account"`
	RolesID      []string `json:"rolesID"`
	DepartmentID string   `json:"departmentID"`
	InterfaceDic []string `json:"interfaceDic"`
	IsAdmin      bool     `json:"isAdmin"`
	Status       bool     `json:"status"`
	CreateTime   string   `json:"createTime"`
	UpdateTime   string   `json:"updateTime"`
}

type UserListResponse struct {
	Total int            `json:"total"`
	List  []UserResponse `json:"list"`
}

type CommonResponse struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data UserListResponse `json:"data"`
}

type GetUserListRequest struct {
	Limit        int32    `form:"limit"`
	Offset       int32    `form:"offset"`
	ID           string   `form:"id,optional"`
	Nickname     string   `form:"nickname,optional"`
	Avatar       string   `form:",optional"`
	Account      string   `form:"account,optional"`
	RolesID      []string `form:"rolesID,optional"`
	DepartmentID string   `form:"departmentID,optional"`
	InterfaceDic []string `form:"interfaceDic,optional"`
	IsAdmin      bool     `form:"isAdmin,optional"`
	Status       bool     `form:"status,optional"`
	CreateTime   string   `form:"createTime,optional"`
	UpdateTime   string   `form:"updateTime,optional"`
}

type GetUserListResponse struct {
	Code int              `json:"code"`
	Msg  string           `json:"msg"`
	Data UserListResponse `json:"data"`
}

type DeleteUserRequest struct {
	ID string `path:"id"`
}

type DeleteUserResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type UpdateUserRequest struct {
	ID           string   `path:"id"`
	Password     string   `form:"password,optional"`
	Nickname     string   `form:"nickname,optional"`
	Avatar       string   `form:"avatar,optional"`
	RolesID      []string `form:"rolesID,optional"`
	DepartmentID string   `form:"departmentID,optional"`
	InterfaceDic []string `form:"interfaceDic,optional"`
	IsAdmin      bool     `form:"isAdmin,optional"`
	Status       bool     `form:"status,optional"`
}

type UpdateUserResponse struct {
	Code int    `json:"code"`
	Msg  string `json:"msg"`
}

type CreateUserRequest struct {
	Nickname     string   `form:"nickname,optional"`
	Avatar       string   `form:"avatar,optional"`
	Account      string   `form:"account"`
	Password     string   `form:"password"`
	RolesID      []string `form:"rolesID,optional"`
	DepartmentID string   `form:"departmentID,optional"`
	InterfaceDic []string `form:"interfaceDic,optional"`
	IsAdmin      bool     `form:"isAdmin,optional"`
	Status       bool     `form:"status,optional"`
}
