// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"micro/api/auth/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/auth/captcha",
				Handler: CaptchaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
