export default {
  translation: {
    login: 'Sign in',
    title: 'Go-React-Admin',
    welcome: 'Welcome to the management System',
    slogan: 'A General Management System Developed Based on Golang',
    description: 'A universal management System developed based on Go language, designed to provide a better learning platform for more beginners',
    completeAccount: 'Account',
    completePassword: 'Password',
    completeCaptcha: 'Captcha',
    accountRequired: 'Account is Required',
    passwordRequired: 'Password is Required',
    captchaRequired: 'Captcha is Required',
    closeLeft: 'CloseLeft',
    closeRight: 'CloseRight',
    closeOther: 'CloseOther',
    refreshTab: 'RefreshTab',
    commitTitle: 'Contributions in the last year',
    commitCount: 'Commits Count',
    memUsageTotal: 'MemUsage Total',
    memUsageAvailable: 'MemUsage Available',
    memUsageInUsed: 'MemUsage Used',
    memUsagePercent: 'MemUsage Percent',
    memUsageInFree: 'MemUsage Free',
    memUsageActive: 'MemUsage Active',
    memUsageInactive: 'MemUsage Inactive',
    memUsageWired: 'MemUsage Wired',
    memUsageLaundry: 'MemUsage Laundry',
    commitBlameTitle: 'Blame Logs',
    quickStart: 'Quick Enter',
    refresh: 'Refresh',
    reset: 'Reset',
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    id: 'ID',
    account: 'Account',
    password: 'Password',
    nickName: 'NickName',
    role: 'Role',
    department: 'Department',
    status: 'Status',
    createTime: 'CreateTime',
    updateTime: 'UpdateTime',
    operate: 'Operate',
    on: 'On',
    off: 'Off',
    normalMan: 'Normal',
    superMan: 'SystemAccount',
    roleName: 'RoleName',
    roleDescription: 'Description',
    index: 'Index',
    confirm: 'Confirm',
    cancel: 'Cancel',
    permissionEdit: 'PermissionEdit',
    menusPermission: 'MenusPermission',
    resourcePermission: 'ResourcePermission',
    authUser: 'AuthUser',
    remove: 'Remove',
  },
};
