export default {
  translation: {
    login: 'Sign in',
    logout: 'Sign out',
    title: 'Go-React-Admin',
    welcome: 'Welcome to the management System',
    slogan: 'A General Management System Developed Based on Golang',
    description: 'A universal management System developed based on Go language, designed to provide a better learning platform for more beginners',
    completeAccount: 'Account',
    completePassword: 'Password',
    completeCaptcha: 'Captcha',
    pleaseEnter: 'PleaseEnter',
    accountRequired: 'Account is Required',
    passwordRequired: 'Password is Required',
    captchaRequired: 'Captcha is Required',
    closeLeft: 'CloseLeft',
    closeRight: 'CloseRight',
    closeOther: 'CloseOther',
    refreshTab: 'RefreshTab',
    commitTitle: 'Contributions in the last year',
    commitCount: 'Commits Count',
    memUsageTotal: 'MemUsage Total',
    memUsageAvailable: 'MemUsage Available',
    memUsageInUsed: 'MemUsage Used',
    memUsagePercent: 'MemUsage Percent',
    memUsageInFree: 'MemUsage Free',
    memUsageActive: 'MemUsage Active',
    memUsageInactive: 'MemUsage Inactive',
    memUsageWired: 'MemUsage Wired',
    memUsageLaundry: 'MemUsage Laundry',
    commitBlameTitle: 'Blame Logs',
    quickStart: 'Quick Enter',
    refresh: 'Refresh',
    reset: 'Reset',
    search: 'Search',
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    id: 'ID',
    account: 'Account',
    password: 'Password',
    nickName: 'NickName',
    role: 'Role',
    department: 'Department',
    status: 'Status',
    createTime: 'CreateTime',
    updateTime: 'UpdateTime',
    operate: 'Operate',
    on: 'On',
    off: 'Off',
    normalMan: 'Normal',
    superMan: 'SystemAccount',
    roleName: 'RoleName',
    roleDescription: 'Description',
    index: 'Index',
    confirm: 'Confirm',
    cancel: 'Cancel',
    export: 'Export',
    permissionEdit: 'PermissionEdit',
    menusPermission: 'MenusPermission',
    resourcePermission: 'ResourcePermission',
    authUser: 'AuthUser',
    auth: 'Auth',
    readyAuthUser: 'ReadyAuthUser',
    notAuthUser: 'NotAuthUser',
    remove: 'Remove',
    departmentName: 'Name',
    addChildDepartment: 'Add',
    departmentList: 'DepartmentList',
    departmentDescription: 'Description',
    parentDepartment: 'ParentDepartment',
    order: 'Order',
    menuList: 'MenuList',
    menuName: 'MenuName',
    menuIcon: 'Icon',
    menuPath: 'Path',
    menuComponent: 'Component',
    menuType: 'Type',
    isOutSite: 'IsOutSite',
    outSiteLink: 'OutSiteLink',
    routeInnerType: 'InnerRoute',
    routeExternalType: 'External',
    addMenu: 'AddChild',
    resource: 'Resource',
    interfaceDic: 'Directive',
    interfaceName: 'Name',
    interfacePath: 'Path',
    interfaceMethod: 'Method',
    interfaceDesc: 'Description',
    requestMethod: 'Method',
    requestPath: 'Path',
    requestDuration: 'Duration',
    requestStatus: 'Status',
    fileList: 'FileList',
    uploadFile: 'UploadFile',
    download: 'Download',
    fileName: 'FileName',
    fileSize: 'FileSize',
    uploadUser: 'UploadUser',
    uploadTime: 'UploadTime',
    progress: 'Progress',
    calculateFileHash: 'CalculateFileHash,waiting...',
    startUpload: 'StartUpload',
    uploadFinish: 'UploadFinish',
    continueUploadFile: 'ContinueUploadFile',
    systemLogs: 'SystemLogs',
    timeTask: 'TimeTask',
    taskName: 'TaskName',
    runTimes: 'RunTimes',
    taskStatus: 'Status',
    cron: 'Cron',
    lastRunTime: 'LastRunTime',
    preview: 'Preview',
    downloadZip: 'Download (Zip)',
  },
};
