// Code generated by goctl. DO NOT EDIT.
// Source: captcha.proto

package server

import (
	"context"

	"micro/rpc/captcha/captcha"
	"micro/rpc/captcha/internal/logic"
	"micro/rpc/captcha/internal/svc"
)

type CaptchaServiceServer struct {
	svcCtx *svc.ServiceContext
	captcha.UnimplementedCaptchaServiceServer
}

func NewCaptchaServiceServer(svcCtx *svc.ServiceContext) *CaptchaServiceServer {
	return &CaptchaServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *CaptchaServiceServer) GenerateCaptcha(ctx context.Context, in *captcha.GenerateCaptchaRequest) (*captcha.GenerateCaptchaResponse, error) {
	l := logic.NewGenerateCaptchaLogic(ctx, s.svcCtx)
	return l.GenerateCaptcha(in)
}

func (s *CaptchaServiceServer) VerifyCaptcha(ctx context.Context, in *captcha.VerifyCaptchaRequest) (*captcha.VerifyCaptchaResponse, error) {
	l := logic.NewVerifyCaptchaLogic(ctx, s.svcCtx)
	return l.VerifyCaptcha(in)
}
